project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('sr.urls', namespace='sr')),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'form.html', }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html', }, name='logout'),
    url(r'^admin/', include(admin.site.urls)),
)

sr/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', 'sr.views.dashboard', name='dashboard'),
    url(r'^rate/(?P<girl_pk>\d+)/$', 'sr.views.rate', name='rate'),
    url(r'^add-girl/$', 'sr.views.girl_form', name='add_girl'),
    url(r'^edit-girl/(?P<girl_pk>\d+)/$', 'sr.views.girl_form', name='edit_girl'),
    url(r'^girl-detail/(?P<girl_pk>\d+)/$', 'sr.views.girl_detail', name='girl_detail'),
)

sr/models.py
from django.db import models

from django.contrib.auth.models import User


class Girl(models.Model):
    name = models.CharField(max_length=128)
    facebook_link = models.URLField(null=True, blank=True)
    picture_link = models.URLField(null=True, blank=True)
    nominated_by = models.ForeignKey(User)

    class Meta:
        ordering = ('-pk', )

    def __unicode__(self):
        return u'%s' % self.name

    def get_rank_by_user(self, user):
        return GirlRank.get(girl=self, user=user)

    def get_avg_rank(self):
        ranks = []
        for user in User.objects.all():
            rank = self.get_rank_by_user(user=user)
            if rank:
                ranks.append(rank.rank)
        try:
            return sum(ranks) / len(ranks)
        except ZeroDivisionError:
            return None

    def get_rank_count(self):
        count = 0
        for user in User.objects.all():
            rank = self.get_rank_by_user(user=user)
            if rank:
                count += 1
        return count

    def get_max_rate(self):
        ranks = []
        min_ranks = []
        for user in User.objects.all():
            rank = self.get_rank_by_user(user)
            if rank:
                ranks.append(rank)
        if len(ranks) == 0:
            return None
        ranks = sorted(ranks, key=lambda obj: obj.rank)
        ranks = list(reversed(ranks))
        min_rank = ranks[0].rank
        for rank in ranks:
            if rank.rank == min_rank:
                min_ranks.append(rank)
            else:
                return min_ranks
        return min_ranks

    def get_min_rate(self):
        ranks = []
        min_ranks = []
        for user in User.objects.all():
            rank = self.get_rank_by_user(user)
            if rank:
                ranks.append(rank)
        if len(ranks) == 0:
            return None
        ranks = sorted(ranks, key=lambda obj: obj.rank)
        min_rank = ranks[0].rank
        for rank in ranks:
            if rank.rank == min_rank:
                min_ranks.append(rank)
            else:
                return min_ranks
        return min_ranks

    def get_history_max_rate(self):
        min_ranks = []
        ranks = GirlRank.objects.filter(girl=self).order_by('-rank')
        if len(ranks) == 0:
            return None
        min_rank = ranks[0].rank
        for rank in ranks:
            if rank.rank == min_rank:
                min_ranks.append(rank)
            else:
                return min_ranks
        return min_ranks

    def get_history_min_rate(self):
        min_ranks = []
        ranks = GirlRank.objects.filter(girl=self).order_by('rank')
        if len(ranks) == 0:
            return None
        min_rank = ranks[0].rank
        for rank in ranks:
            if rank.rank == min_rank:
                min_ranks.append(rank)
            else:
                return min_ranks
        return min_ranks

    def get_comments_count(self):
        return self.girlcomment_set.filter(deleted=False).count()


class GirlRank(models.Model):
    RANKS = zip(map(lambda n: n/2.0, range(0, 21)), map(lambda n: n/2.0, range(0, 21)))
    girl = models.ForeignKey(Girl)
    user = models.ForeignKey(User)
    rank = models.DecimalField(decimal_places=1, max_digits=3, choices=RANKS)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s: %s %s' % (self.user, self.girl, self.rank)

    class Meta:
        ordering = ('-timestamp', )

    @staticmethod
    def get(girl, user):
        try:
            return GirlRank.objects.filter(user=user, girl=girl)[0]
        except IndexError:
            return None


class GirlComment(models.Model):
    girl = models.ForeignKey(Girl)
    user = models.ForeignKey(User)
    deleted = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __unicode__(self):
        return u'%s: %s, %s' % (self.user, self.girl, self.text[:20])

class Stream(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    class Meta:
        ordering = ('-timestamp', )

    def __unicode__(self):
        return u'%s: %s (%s)' % (self.user, self.text[:20], self.timestamp)

sr/forms.py
from django import forms

from .models import GirlRank, Girl, GirlComment


class RateForm(forms.ModelForm):
    class Meta:
        model = GirlRank
        fields = ('rank', )

    def __init__(self, girl, user, *args, **kwargs):
        super(RateForm, self).__init__(*args, **kwargs)

        self.girl = girl
        self.user = user

    def save(self, commit=True):
        obj = super(RateForm, self).save(commit=False)
        obj.user = self.user
        obj.girl = self.girl
        if commit:
            obj.save()
        return obj


class GirlForm(forms.ModelForm):
    class Meta:
        model = Girl
        exclude = ('nominated_by', )

    def __init__(self, user, *args, **kwargs):
        super(GirlForm, self).__init__(*args, **kwargs)

        self.user = user

    def save(self, commit=True):
        obj = super(GirlForm, self).save(commit=False)
        obj.nominated_by = self.user
        if commit:
            obj.save()
        return obj


class CommentForm(forms.ModelForm):
    class Meta:
        model = GirlComment
        fields = ('text', )

    def __init__(self, girl, user, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        self.girl = girl
        self.user = user

    def save(self, commit=True):
        obj = super(CommentForm, self).save(commit=False)
        obj.user = self.user
        obj.girl = self.girl
        if commit:
            obj.save()
        return obj

sr/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

from .models import Girl, Stream
from .forms import RateForm, GirlForm, CommentForm

def _can_be_int(num):
    try:
        int(num)
        return True
    except (ValueError, TypeError):
        return False

@login_required
def dashboard(request):
    order_by = request.GET.get('order_by')  # options = 'name', 'avg', user rank (int)

    girls = Girl.objects.all()
    users = User.objects.all()
    stream = Stream.objects.all()[:53]

    if order_by in ('name', '-name'):
        girls = girls.order_by(order_by)
    elif order_by in ('avg', '-avg'):
        girls = sorted(girls, key=lambda obj: obj.get_avg_rank())
        if order_by == '-avg':
            girls = reversed(girls)
    elif _can_be_int(order_by):
        order_by = int(order_by)
        girls = sorted(girls, key=lambda obj: getattr(obj.get_rank_by_user(abs(order_by)), 'rank', 0))
        if order_by < 0:
            girls = reversed(girls)


    return render(request, 'dashboard.html', {
        'girls': girls,
        'users': users,
        'stream': stream,
    })


@login_required
def rate(request, girl_pk):
    girl = get_object_or_404(Girl, pk=girl_pk)
    form = RateForm(girl=girl, user=request.user, data=request.POST or None)
    if form.is_valid():
        obj = form.save()
        Stream(user=request.user, text=u'rated %s with %s points' % (girl.name, obj.rank)).save()
        return HttpResponseRedirect(reverse('sr:dashboard'))
    return render(request, 'form.html', {
        'form': form,
    })


@login_required
def girl_form(request, girl_pk=None):
    if girl_pk:
        girl = get_object_or_404(Girl, pk=girl_pk)
        form = GirlForm(user=request.user, data=request.POST or None, instance=girl)
    else:
        form = GirlForm(user=request.user, data=request.POST or None)
    if form.is_valid():
        obj = form.save()
        if not girl_pk:
            Stream(user=request.user, text=u'added %s' % (obj.name)).save()
        else:
            Stream(user=request.user, text=u'edited %s profile' % (obj.name)).save()

        return HttpResponseRedirect(reverse('sr:dashboard'))
    return render(request, 'form.html', {
        'form': form,
    })


@login_required
def girl_detail(request, girl_pk):
    girl = get_object_or_404(Girl, pk=girl_pk)
    comments = girl.girlcomment_set.filter(deleted=False).order_by('-timestamp')
    comment_form = CommentForm(girl=girl, user=request.user, data=request.POST or None)
    if comment_form.is_valid():
        obj = comment_form.save()
        Stream(user=request.user, text=u'commented %s: %s' % (girl.name, obj.text)).save()
        return HttpResponseRedirect('')
    return render(request, 'girl_detail.html', {
        'girl': girl,
        'comments': comments,
        'comment_form': comment_form,
    })

sr/templates/base.html
{% load sr_tags %}

<title>SR</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<style>
th {
    text-align: left;
}
td {
    padding-right: 10px;
}
</style>

<a href="{% url 'sr:dashboard' %}">dashboard</a>
<a href="{% url 'sr:add_girl' %}">add girl</a>
<a href="{% url 'logout' %}">logout</a>

{% block content %}
{% endblock content %}

<hr>
<p><b>Pravidla SR:</b>
<br>1. Nemluvíš o SR
<br>2. Nemluvíš o SR
<br>3. Pokud přidáváš holku, musí jí znát alespoň 3 uživatelé
<br>4. Hodnotíš pouze holku, kterou jsi viděl osobně
<br>5. Hodnotíš pouze vzhled (jediná výjimka je JT, protože je to kráva)
<br>6. Přidáváš pouze holky 15+<p>
<hr>
SR, founded 14. 6. 2014

sr/templates/dashboard.html
{% extends 'base.html' %}
{% load sr_tags %}


{% block content %}
<table>
    <tr>
        <th>
            Girl
            <a href="?order_by=name">+</a>
            <a href="?order_by=-name">-</a>
        </th>
        <th>
            Avg
            <a href="?order_by=-avg">+</a>
            <a href="?order_by=avg">-</a>
        </th>
        {% for user in users %}
            <th>
                {{ user }}
                <a href="?order_by=-{{ user.pk }}">+</a>
                <a href="?order_by={{ user.pk }}">-</a>
            </th>
        {% endfor %}
    </tr>
    {% for girl in girls %}
        <tr style="{% if forloop.counter|divisibleby:2 == 0 %}background: EEEEEE;{% endif %}">
            <td>
                <a href="{% url 'sr:girl_detail' girl.pk %}"><b>{{ girl }}</b> ({{ girl.get_comments_count }})</a>
                {% if girl.facebook_link %}
                    <a href="{{ girl.facebook_link }}" target="_blank">FB</a>
                {% endif %}
                {% if girl.picture_link %}
                    <a href="{{ girl.picture_link }}" target="_blank">pic</a>
                {% endif %}
                <a href="{% url 'sr:rate' girl.pk %}">rate</a>
                <a href="{% url 'sr:edit_girl' girl.pk %}">edit</a>
            </td>
            <td><b>{% rank girl.get_avg_rank %}</b> ({{ girl.get_rank_count }})</td>
            {% for user in users %}
                <td>{% rank_girl_user girl user %}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
<hr>
<p><b>Timeline</b></p>
{% for msg in stream %}
<p>{% if msg.user %}<b>{{ msg.user }}</b>{% endif %}{{ msg.text }} - {{ msg.timestamp }}</p>
{% endfor %}
{% endblock content %}

sr/templates/form.html
{% extends 'base.html' %}
{% load sr_tags %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

sr/templates/girl_detail.html
{% extends 'base.html' %}
{% load sr_tags %}

{% block content %}
<h1>{{ girl.name }}</h1>
<table>
    <tr>
        <th>Avg</th>
        <td>{% rank girl.get_avg_rank %}</td>
    </tr>
    <tr>
        <th>Rates</th>
        <td>{{ girl.get_rank_count }}</td>
    </tr>
    <tr>
        <th>Max (actual)</th>
        <td>
            {% for rank in  girl.get_max_rate %}
                {{ rank.user }}: {{ rank.rank }},
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Min (actual)</th>
        <td>
            {% for rank in  girl.get_min_rate %}
                {{ rank.user }}: {{ rank.rank }},
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Max (history)</th>
        <td>
            {% for rank in  girl.get_history_max_rate %}
                {{ rank.user }}: {{ rank.rank }},
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Min (history)</th>
        <td>
            {% for rank in  girl.get_history_min_rate %}
                {{ rank.user }}: {{ rank.rank }},
            {% endfor %}
        </td>
    </tr>
</table>

<h2>Comments</h2>

<form method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="Submit">
</form>

{% for comment in comments %}
    <p><b>{{ comment.user }}</b>: {{ comment.text }} ({{ comment.timestamp }})</p>
{% endfor %}
{% endblock content %}

sr/templates/logout.html
You are successful logged out. <a href="{% url 'login' %}">Login again</a>